/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-southeast-1",
  aws_appsync_graphqlEndpoint:
    "https://uwxuf74dzfatjomcrfkrfp5wka.appsync-api.ap-southeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-southeast-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-rij3bur3gjf5jjeesjnvib7fei",
  aws_cognito_identity_pool_id:
    "ap-southeast-1:944965e1-e30a-46be-a6d4-c4096d20d593",
  aws_cognito_region: "ap-southeast-1",
  aws_user_pools_id: "ap-southeast-1_kjRee9rFb",
  aws_user_pools_web_client_id: "75tu88tmtu5mt6p7kuvlbd2e5k",
  oauth: {},
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsmobile;
