export const doctors = [
  {
    id: 1,
    name: "John Doe",
    speciality: "Heart Specialist",
    image: "https://randomuser.me/api/portraits/men/69.jpg",
    description: "Hello, I am a nice doctor",
  },
  {
    id: 2,
    name: "Hassan Abbasi",
    speciality: "Expert in Cardiology",
    image: "https://randomuser.me/api/portraits/men/74.jpg",
    description: "Hello, I am a cool doctor",
  },
  {
    id: 3,
    name: "Ahmad Feroz",
    speciality: "Brain Surgeon",
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    description: "Hello, I am a good doctor",
  },
  {
    id: 3,
    name: "Ahmad Feroz",
    speciality: "Brain Surgeon",
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    description: "Hello, I am a good doctor",
  },
  {
    id: 3,
    name: "Ahmad Feroz",
    speciality: "Brain Surgeon",
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    description: "Hello, I am a good doctor",
  },
  {
    id: 3,
    name: "Ahmad Feroz",
    speciality: "Brain Surgeon",
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    description: "Hello, I am a good doctor",
  },
  {
    id: 3,
    name: "Ahmad Feroz",
    speciality: "Brain Surgeon",
    image: "https://randomuser.me/api/portraits/men/73.jpg",
    description: "Hello, I am a good doctor",
  },
];